### ISSUE TITLE
When selecting Logs (uilogs) in the sidebar, the main page page stays empty

### ISSUE THREAD

**Issue by bouwew** [custom-components/uilogs#16] opened 2020-09-21 06:09 UTC
Only when I right-click and press reload, then the log-data is shown.

When I next click e.g. Overview, the page shows an error-message: `error while loading page lovelace`.

This is the error I see in Logs:
```
Logger: frontend.js.latest.202009180
Source: components/system_log/__init__.py:193
First occurred: 8:03:17 AM (2 occurrences)
Last logged: 8:03:17 AM

http://192.168.0.123:8123/api/panel_custom/uilogs:20:11471 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-list-item" has already been used with this registry
```

My system:
```
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.63
python_version | 3.8.5
supervisor | 245
timezone | Europe/Amsterdam
version | 0.115.2
virtualenv | false
```

**Comment by ludeeus** [comment] 2020-09-21 06:59
Duplicate of #15

**Closed as completed by ludeeus** 2020-09-21 06:59 UTC
